services:
  backend:
    build: .
    container_name: beyblade-x-backend
    restart: unless-stopped
    volumes:
      - ${HOME}/.beyblade-x-app:/root/.beyblade-x-app
    env_file:
      - .env
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
