services:
  backend:
    build: .
    container_name: beyblade-x-backend
    restart: unless-stopped
    volumes:
      - ${HOME}/.beyblade-x-app:/root/.beyblade-x-app
    env_file:
      - .env
    networks:
      - npm-prod_default

networks:
  npm-prod_default:
    external: true
